import { useEffect, useState } from 'react';
import api from '../services/api';

const VerifiedGuidance = ({ symptoms, specialty, severity, durationInDays }) => {
  const [guidance, setGuidance] = useState([]);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!specialty) {
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError('');
    setGuidance([]);
    setAutoGenerated(false);
    const payload = { symptoms, recommendedSpecialty: specialty };
    if (severity) payload.severity = severity;
    if (durationInDays) payload.durationInDays = durationInDays;
    api
      .post('/remedies/match', payload)
      .then(({ data }) => {
        if (!cancelled) {
          setGuidance(data.data);
          setAutoGenerated(Boolean(data.autoGenerated));
        }
      })
      .catch(() => {
        if (!cancelled) setError('Could not load doctor-prepared guidance.');
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [symptoms, specialty, severity, durationInDays]);

  if (!specialty) {
    return null;
  }

  if (loading) {
    return <p className="muted">Searching doctor-prepared guidance...</p>;
  }

  if (error) {
    return <p className="muted">{error}</p>;
  }

  if (guidance.length === 0) {
    return (
      <p className="muted">
        No guidance is available for this combination. Follow the advice of your treating doctor.
      </p>
    );
  }

  return (
    <div className="verified-guidance">
      <h4>
        {autoGenerated
          ? 'Auto-generated preliminary self-care guidance'
          : 'Doctor-verified temporary guidance'}
      </h4>
      <p className="guidance-note">
        {autoGenerated
          ? 'This preliminary self-care guidance was generated automatically and is educational only — it is NOT a prescription or a diagnosis. Always consult a qualified doctor.'
          : 'These entries were reviewed and approved before publication. They are educational only and not a diagnosis.'}
      </p>
      {guidance.map((item) => (
        <div className="card guidance-item" key={item._id}>
          <h5>{item.probableConditionCategory}</h5>
          <p className="muted">
            For: {item.symptoms.map((s) => s.name).join(', ')} · {item.recommendedSpecialty}
          </p>
          <p>{item.safeTemporaryGuidance}</p>
          {item.precautions?.length > 0 && (
            <ul className="guidance-list">
              {item.precautions.map((line) => (
                <li key={line}>Precaution: {line}</li>
              ))}
            </ul>
          )}
          {item.avoid?.length > 0 && (
            <ul className="guidance-list">
              {item.avoid.map((line) => (
                <li key={line}>Avoid: {line}</li>
              ))}
            </ul>
          )}
          {item.emergencyWarningSigns?.length > 0 && (
            <div className="warning-signs">
              <strong>Seek urgent care if you notice:</strong>
              <ul>
                {item.emergencyWarningSigns.map((line) => (
                  <li key={line}>{line}</li>
                ))}
              </ul>
            </div>
          )}
          <p className="disclaimer">{item.disclaimer}</p>
          {item.isAutoGenerated ? (
            <p className="muted">Generated automatically · Not reviewed by a doctor</p>
          ) : (
            <p className="muted">
              Verified by {item.approval?.approvedBy?.name || 'a medical admin'} · Submitted by
              Dr. {item.doctor?.name || 'Unknown'}
            </p>
          )}
        </div>
      ))}
    </div>
  );
};

export default VerifiedGuidance;